import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Avatar, AvatarFallback, AvatarImage } from '../ui/avatar';
import { Button } from '../ui/button';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '../ui/dropdown-menu';
import { ChevronDown, User, Shield, Settings, LogOut } from 'lucide-react';
import { userProfile } from '../data/navigationData';
import { getInitials } from '../utils/navigationUtils';
export function UserProfileDropdown({ onOpenProfile }) {
    return (_jsxs(DropdownMenu, { children: [_jsx(DropdownMenuTrigger, { asChild: true, children: _jsxs(Button, { variant: "ghost", className: "flex items-center gap-3 hover:bg-accent hover:text-accent-foreground transition-colors h-10 px-3", children: [_jsxs(Avatar, { className: "h-7 w-7", children: [_jsx(AvatarImage, { src: userProfile.avatar }), _jsx(AvatarFallback, { children: getInitials(userProfile.name) })] }), _jsxs("div", { className: "hidden md:block text-left", children: [_jsx("p", { className: "text-sm font-medium text-foreground", children: userProfile.name }), _jsx("p", { className: "text-xs text-muted-foreground", children: userProfile.role })] }), _jsx(ChevronDown, { className: "h-4 w-4 text-muted-foreground" })] }) }), _jsxs(DropdownMenuContent, { align: "end", className: "w-64 bg-popover border-border", children: [_jsx(DropdownMenuLabel, { children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs(Avatar, { className: "h-8 w-8", children: [_jsx(AvatarImage, { src: userProfile.avatar }), _jsx(AvatarFallback, { children: getInitials(userProfile.name) })] }), _jsxs("div", { children: [_jsx("p", { className: "font-medium text-foreground", children: userProfile.name }), _jsx("p", { className: "text-xs text-muted-foreground", children: userProfile.email })] })] }) }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuItem, { className: "cursor-pointer hover:bg-accent hover:text-accent-foreground", onClick: onOpenProfile, children: [_jsx(User, { className: "mr-2 h-4 w-4" }), "Profile Settings"] }), _jsxs(DropdownMenuItem, { className: "cursor-pointer hover:bg-accent hover:text-accent-foreground", children: [_jsx(Shield, { className: "mr-2 h-4 w-4" }), "Security"] }), _jsxs(DropdownMenuItem, { className: "cursor-pointer hover:bg-accent hover:text-accent-foreground", children: [_jsx(Settings, { className: "mr-2 h-4 w-4" }), "Preferences"] }), _jsx(DropdownMenuSeparator, {}), _jsxs(DropdownMenuItem, { className: "cursor-pointer text-destructive hover:bg-destructive/10 hover:text-destructive", children: [_jsx(LogOut, { className: "mr-2 h-4 w-4" }), "Sign Out"] })] })] }));
}
//# sourceMappingURL=UserProfileDropdown.js.map