import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Search, Bell, User, Menu } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Avatar, AvatarFallback, AvatarImage } from './ui/avatar';
import { Badge } from './ui/badge';
export function TopNavigation({ onMenuClick }) {
    return (_jsxs("header", { className: "h-16 bg-white border-b border-gray-200 px-6 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-4", children: [_jsx(Button, { variant: "ghost", size: "icon", onClick: onMenuClick, className: "lg:hidden", children: _jsx(Menu, { className: "h-5 w-5" }) }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-white font-semibold text-sm", children: "SC" }) }), _jsxs("div", { className: "hidden sm:block", children: [_jsx("h1", { className: "font-semibold text-gray-900", children: "SupplyChain Pro" }), _jsx("p", { className: "text-xs text-gray-500", children: "Enterprise Platform" })] })] })] }), _jsx("div", { className: "flex-1 max-w-md mx-4", children: _jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" }), _jsx(Input, { placeholder: "Search vehicles, trips, drivers...", className: "pl-10 bg-gray-50 border-gray-200" })] }) }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsxs(Button, { variant: "ghost", size: "icon", className: "relative", children: [_jsx(Bell, { className: "h-5 w-5 text-gray-600" }), _jsx(Badge, { className: "absolute -top-1 -right-1 h-5 w-5 p-0 bg-red-500 text-white text-xs flex items-center justify-center", children: "3" })] }), _jsxs("div", { className: "flex items-center gap-2 ml-2", children: [_jsxs(Avatar, { className: "h-8 w-8", children: [_jsx(AvatarImage, { src: "/api/placeholder/32/32" }), _jsx(AvatarFallback, { className: "bg-blue-100 text-blue-600", children: "JD" })] }), _jsxs("div", { className: "hidden md:block", children: [_jsx("p", { className: "text-sm font-medium text-gray-900", children: "John Doe" }), _jsx("p", { className: "text-xs text-gray-500", children: "Fleet Manager" })] })] })] })] }));
}
//# sourceMappingURL=TopNavigation.js.map