import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { motion } from 'motion/react';
import { ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router';
import { projects } from '../data/projects'; // Import data
export const Work = () => {
    return (_jsx("div", { className: "bg-neutral-950 min-h-screen text-white pt-32 px-6", children: _jsxs("div", { className: "container mx-auto", children: [_jsx("div", { className: "flex justify-between items-end mb-24", children: _jsxs("div", { children: [_jsx(Link, { to: "/", className: "text-xs font-mono uppercase tracking-widest text-neutral-500 hover:text-white transition-colors mb-8 block", children: "\u2190 Back to Home" }), _jsxs("h1", { className: "text-6xl md:text-9xl font-medium tracking-tighter leading-[0.9]", children: ["Archive ", _jsx("br", {}), _jsx("span", { className: "italic font-serif text-neutral-500", children: "2021\u201424" })] })] }) }), _jsx("div", { className: "grid md:grid-cols-2 lg:grid-cols-3 gap-8 gap-y-16 pb-32", children: projects.map((project, index) => (_jsx(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { delay: index * 0.1 }, className: "group cursor-pointer", children: _jsxs(Link, { to: `/work/${project.slug}`, children: [_jsxs("div", { className: "relative overflow-hidden aspect-[3/4] mb-6 bg-neutral-900 rounded-sm", children: [_jsx("img", { src: project.image, alt: project.title, className: "object-cover w-full h-full opacity-80 group-hover:scale-105 group-hover:opacity-100 transition-all duration-700" }), _jsx("div", { className: "absolute inset-0 bg-black/20 group-hover:bg-transparent transition-colors" }), _jsx("div", { className: "absolute bottom-4 right-4 bg-white/10 backdrop-blur-md p-3 rounded-full opacity-0 group-hover:opacity-100 translate-y-4 group-hover:translate-y-0 transition-all duration-500", children: _jsx(ArrowUpRight, { className: "w-5 h-5 text-white" }) })] }), _jsxs("div", { className: "flex justify-between items-baseline border-t border-white/10 pt-4", children: [_jsxs("div", { children: [_jsx("h3", { className: "text-xl font-medium tracking-tight mb-1", children: project.title }), _jsx("p", { className: "text-xs font-mono uppercase tracking-widest text-neutral-500", children: project.category })] }), _jsx("span", { className: "text-xs font-mono text-neutral-600", children: project.year })] })] }) }, project.id))) })] }) }));
};
//# sourceMappingURL=Work.js.map