import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Plus, Minus, Star } from 'lucide-react';
import { Button } from './ui/button';
import { Card, CardContent } from './ui/card';
import { Badge } from './ui/badge';
import { ImageWithFallback } from './figma/ImageWithFallback';
export function ProductCard({ product, cartQuantity, onAddToCart, onRemoveFromCart }) {
    return (_jsx(Card, { className: "group hover:shadow-lg transition-shadow duration-200", children: _jsxs(CardContent, { className: "p-4", children: [_jsxs("div", { className: "relative mb-3", children: [_jsx(ImageWithFallback, { src: product.image, alt: product.name, className: "w-full h-32 object-cover rounded-lg" }), product.organic && (_jsx(Badge, { className: "absolute top-2 left-2 bg-green-100 text-green-800", children: "Organic" })), product.originalPrice && (_jsx(Badge, { className: "absolute top-2 right-2 bg-red-100 text-red-800", children: "Sale" }))] }), _jsx("h3", { className: "mb-2 line-clamp-2", children: product.name }), _jsxs("div", { className: "flex items-center mb-2 text-sm text-gray-600", children: [_jsx(Star, { className: "h-3 w-3 fill-yellow-400 text-yellow-400 mr-1" }), _jsx("span", { children: product.rating }), _jsx("span", { className: "mx-1", children: "\u2022" }), _jsxs("span", { children: [product.reviews, " reviews"] })] }), _jsx("div", { className: "flex items-center justify-between mb-3", children: _jsxs("div", { children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsxs("span", { className: "font-semibold text-lg", children: ["$", product.price.toFixed(2)] }), product.originalPrice && (_jsxs("span", { className: "text-sm text-gray-500 line-through", children: ["$", product.originalPrice.toFixed(2)] }))] }), _jsxs("span", { className: "text-sm text-gray-500", children: ["per ", product.unit] })] }) }), _jsx("div", { className: "flex items-center justify-between", children: cartQuantity === 0 ? (_jsxs(Button, { onClick: () => onAddToCart(product), disabled: !product.inStock, className: "w-full bg-green-600 hover:bg-green-700", size: "sm", children: [_jsx(Plus, { className: "h-4 w-4 mr-2" }), product.inStock ? 'Add to Cart' : 'Out of Stock'] })) : (_jsxs("div", { className: "flex items-center justify-center space-x-3 w-full", children: [_jsx(Button, { variant: "outline", size: "sm", onClick: () => onRemoveFromCart(product.id), className: "h-8 w-8 p-0", children: _jsx(Minus, { className: "h-3 w-3" }) }), _jsx("span", { className: "font-medium min-w-[20px] text-center", children: cartQuantity }), _jsx(Button, { size: "sm", onClick: () => onAddToCart(product), className: "h-8 w-8 p-0 bg-green-600 hover:bg-green-700", children: _jsx(Plus, { className: "h-3 w-3" }) })] })) })] }) }));
}
//# sourceMappingURL=ProductCard.js.map