"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "motion/react";
export function PageSkeleton({ type = 'content' }) {
    const pulseAnimation = {
        animate: {
            opacity: [0.4, 0.8, 0.4],
        },
        transition: {
            duration: 1.5,
            repeat: Infinity,
            ease: "easeInOut"
        }
    };
    if (type === 'hero') {
        return (_jsxs("div", { className: "min-h-screen bg-background", children: [_jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-16", children: _jsxs("div", { className: "text-center", children: [_jsx(motion.div, { ...pulseAnimation, className: "h-16 bg-muted rounded-lg mb-6 max-w-4xl mx-auto" }), _jsx(motion.div, { ...pulseAnimation, className: "h-6 bg-muted rounded-lg mb-8 max-w-2xl mx-auto" }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-4 justify-center mb-16", children: [_jsx(motion.div, { ...pulseAnimation, className: "h-12 bg-blue-200 dark:bg-blue-800 rounded-lg w-40" }), _jsx(motion.div, { ...pulseAnimation, className: "h-12 bg-muted rounded-lg w-40" })] })] }) }), _jsx("div", { className: "space-y-20", children: [1, 2, 3].map((section) => (_jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsx(motion.div, { ...pulseAnimation, className: "h-8 bg-muted rounded-lg mb-4 max-w-md mx-auto" }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg mb-8 max-w-lg mx-auto" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6", children: [1, 2, 3].map((card) => (_jsxs(motion.div, { ...pulseAnimation, className: "glass p-6 rounded-2xl space-y-4", children: [_jsx("div", { className: "h-6 bg-muted rounded-lg" }), _jsx("div", { className: "h-4 bg-muted rounded-lg" }), _jsx("div", { className: "h-4 bg-muted rounded-lg w-3/4" })] }, card))) })] }, section))) })] }));
    }
    if (type === 'dashboard') {
        return (_jsx("div", { className: "min-h-screen bg-background p-6", children: _jsxs("div", { className: "max-w-7xl mx-auto", children: [_jsxs("div", { className: "mb-8", children: [_jsx(motion.div, { ...pulseAnimation, className: "h-8 bg-muted rounded-lg mb-2 max-w-xs" }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg max-w-md" })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-6 mb-8", children: [1, 2, 3, 4].map((stat) => (_jsxs(motion.div, { ...pulseAnimation, className: "glass p-6 rounded-2xl space-y-3", children: [_jsx("div", { className: "h-4 bg-muted rounded-lg w-1/2" }), _jsx("div", { className: "h-8 bg-muted rounded-lg" }), _jsx("div", { className: "h-3 bg-muted rounded-lg w-1/3" })] }, stat))) }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsx("div", { className: "lg:col-span-2", children: _jsx(motion.div, { ...pulseAnimation, className: "glass p-6 rounded-2xl h-96" }) }), _jsxs("div", { className: "space-y-6", children: [_jsx(motion.div, { ...pulseAnimation, className: "glass p-6 rounded-2xl h-48" }), _jsx(motion.div, { ...pulseAnimation, className: "glass p-6 rounded-2xl h-40" })] })] })] }) }));
    }
    if (type === 'simple') {
        return (_jsx("div", { className: "min-h-screen bg-background flex items-center justify-center", children: _jsxs("div", { className: "text-center space-y-4", children: [_jsx(motion.div, { className: "w-12 h-12 border-4 border-blue-200 border-t-blue-600 rounded-full mx-auto", animate: { rotate: 360 }, transition: { duration: 1, repeat: Infinity, ease: "linear" } }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg w-32 mx-auto" })] }) }));
    }
    // Default content skeleton
    return (_jsxs("div", { className: "min-h-screen bg-background", children: [_jsx("div", { className: "bg-gradient-to-br from-blue-50 to-white dark:from-blue-950/20 dark:to-background py-20", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center", children: [_jsx(motion.div, { ...pulseAnimation, className: "h-12 bg-muted rounded-lg mb-4 max-w-2xl mx-auto" }), _jsx(motion.div, { ...pulseAnimation, className: "h-6 bg-muted rounded-lg mb-8 max-w-xl mx-auto" }), _jsx(motion.div, { ...pulseAnimation, className: "h-12 bg-blue-200 dark:bg-blue-800 rounded-lg max-w-xs mx-auto" })] }) }), _jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16", children: _jsxs("div", { className: "space-y-12", children: [_jsxs("div", { className: "space-y-4", children: [_jsx(motion.div, { ...pulseAnimation, className: "h-6 bg-muted rounded-lg max-w-md" }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg max-w-full" }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg max-w-5xl" }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg max-w-3xl" })] }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6", children: [1, 2, 3, 4, 5, 6].map((card) => (_jsxs(motion.div, { ...pulseAnimation, className: "glass p-6 rounded-2xl space-y-4", children: [_jsx("div", { className: "h-6 bg-muted rounded-lg" }), _jsx("div", { className: "h-4 bg-muted rounded-lg" }), _jsx("div", { className: "h-4 bg-muted rounded-lg w-2/3" }), _jsx("div", { className: "h-8 bg-blue-200 dark:bg-blue-800 rounded-lg w-1/2" })] }, card))) }), _jsxs("div", { className: "space-y-6", children: [_jsx(motion.div, { ...pulseAnimation, className: "h-6 bg-muted rounded-lg max-w-lg" }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-2 gap-8", children: [_jsxs("div", { className: "space-y-4", children: [_jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg" }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg w-5/6" }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg w-4/5" })] }), _jsxs("div", { className: "space-y-4", children: [_jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg" }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg w-3/4" }), _jsx(motion.div, { ...pulseAnimation, className: "h-4 bg-muted rounded-lg w-5/6" })] })] })] })] }) })] }));
}
//# sourceMappingURL=PageSkeleton.js.map