import { jsxs as _jsxs, jsx as _jsx, Fragment as _Fragment } from "react/jsx-runtime";
import { Minus, Plus, Trash2, X } from 'lucide-react';
import { Button } from './ui/button';
import { Sheet, SheetContent, SheetHeader, SheetTitle } from './ui/sheet';
import { Badge } from './ui/badge';
import { Separator } from './ui/separator';
import { ImageWithFallback } from './figma/ImageWithFallback';
import { CartItem } from '../App';
export function ShoppingCart({ isOpen, onClose, items, onRemoveItem, onUpdateQuantity, total, }) {
    return (_jsx(Sheet, { open: isOpen, onOpenChange: onClose, children: _jsxs(SheetContent, { className: "w-full sm:max-w-lg", children: [_jsx(SheetHeader, { children: _jsxs(SheetTitle, { className: "flex items-center justify-between", children: ["Shopping Cart", _jsxs(Badge, { variant: "secondary", children: [items.length, " item", items.length !== 1 ? 's' : ''] })] }) }), _jsx("div", { className: "flex flex-col h-full", children: items.length === 0 ? (_jsx("div", { className: "flex-1 flex items-center justify-center", children: _jsxs("div", { className: "text-center space-y-2", children: [_jsx("p", { className: "text-muted-foreground", children: "Your cart is empty" }), _jsx(Button, { onClick: onClose, variant: "outline", children: "Continue Shopping" })] }) })) : (_jsxs(_Fragment, { children: [_jsx("div", { className: "flex-1 overflow-auto py-4 space-y-4", children: items.map((item) => (_jsxs("div", { className: "flex gap-4 p-4 border rounded-lg", children: [_jsx(ImageWithFallback, { src: item.image, alt: item.name, className: "w-16 h-16 object-cover rounded" }), _jsxs("div", { className: "flex-1 space-y-2", children: [_jsx("h4", { className: "font-medium line-clamp-2", children: item.name }), _jsxs("p", { className: "text-sm text-muted-foreground", children: ["$", item.price.toFixed(2), " each"] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Button, { variant: "outline", size: "sm", onClick: () => onUpdateQuantity(item.id, item.quantity - 1), className: "h-8 w-8 p-0", children: _jsx(Minus, { className: "h-3 w-3" }) }), _jsx("span", { className: "w-8 text-center", children: item.quantity }), _jsx(Button, { variant: "outline", size: "sm", onClick: () => onUpdateQuantity(item.id, item.quantity + 1), className: "h-8 w-8 p-0", children: _jsx(Plus, { className: "h-3 w-3" }) })] }), _jsx(Button, { variant: "ghost", size: "sm", onClick: () => onRemoveItem(item.id), className: "text-destructive hover:text-destructive h-8 w-8 p-0", children: _jsx(Trash2, { className: "h-4 w-4" }) })] }), _jsxs("p", { className: "text-sm font-medium", children: ["Subtotal: $", (item.price * item.quantity).toFixed(2)] })] })] }, item.id))) }), _jsxs("div", { className: "border-t pt-4 space-y-4", children: [_jsxs("div", { className: "flex justify-between items-center", children: [_jsx("span", { className: "text-lg font-medium", children: "Total:" }), _jsxs("span", { className: "text-xl font-medium", children: ["$", total.toFixed(2)] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Button, { className: "w-full", size: "lg", children: "Proceed to Checkout" }), _jsx(Button, { variant: "outline", className: "w-full", onClick: onClose, children: "Continue Shopping" })] })] })] })) })] }) }));
}
//# sourceMappingURL=ShoppingCart.js.map