import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { Card, CardContent } from '../ui/card';
import { Badge } from '../ui/badge';
import { Avatar, AvatarFallback, AvatarImage } from '../ui/avatar';
import { Clock, Fuel } from 'lucide-react';
import { getTransportIcon, getStatusColor } from '../utils/mapUtils';
export function VehicleList({ vehicles, selectedVehicle, onVehicleSelect }) {
    return (_jsxs("div", { className: "space-y-4", children: [_jsxs("h4", { className: "font-medium text-gray-900", children: ["Active Vehicles (", vehicles.length, ")"] }), _jsx("div", { className: "space-y-3 max-h-80 overflow-y-auto", children: vehicles.map((vehicle) => (_jsx(Card, { className: `cursor-pointer transition-all hover:shadow-md ${selectedVehicle === vehicle.id ? 'ring-2 ring-blue-500 bg-blue-50' : 'bg-white'}`, onClick: () => onVehicleSelect(selectedVehicle === vehicle.id ? '' : vehicle.id), children: _jsx(CardContent, { className: "p-3", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "flex-shrink-0", children: getTransportIcon(vehicle.type, vehicle.status) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h5", { className: "font-medium text-gray-900 truncate", children: vehicle.name }), _jsx("p", { className: "text-sm text-gray-600", children: vehicle.id }), _jsxs("div", { className: "flex items-center gap-2 mt-1", children: [_jsx(Badge, { className: getStatusColor(vehicle.status), children: vehicle.status }), vehicle.status === 'In Transit' && (_jsxs("div", { className: "flex items-center gap-1", children: [_jsx(Clock, { className: "h-3 w-3 text-blue-500" }), _jsx("span", { className: "text-xs text-blue-600", children: vehicle.eta })] }))] }), _jsxs("div", { className: "flex items-center justify-between mt-2", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsxs(Avatar, { className: "h-5 w-5", children: [_jsx(AvatarImage, { src: vehicle.driver.photo }), _jsx(AvatarFallback, { className: "text-xs", children: vehicle.driver.name.split(' ').map((n) => n[0]).join('') })] }), _jsx("span", { className: "text-xs text-gray-600", children: vehicle.driver.name })] }), _jsxs("div", { className: "flex items-center gap-1", children: [_jsx(Fuel, { className: "h-3 w-3 text-gray-400" }), _jsxs("span", { className: "text-xs text-gray-600", children: [vehicle.fuelLevel, "%"] })] })] })] })] }) }) }, vehicle.id))) })] }));
}
//# sourceMappingURL=VehicleList.js.map